# Generated by Django 3.2.6 on 2021-08-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatshouldido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFiles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('field_native_filename', models.CharField(db_column='_native_filename', max_length=32)),
                ('field_encr_filename', models.CharField(db_column='_encr_filename', max_length=64, unique=True)),
                ('uploaded_date', models.DateTimeField(auto_now=True)),
                ('field_file_size', models.IntegerField(db_column='_filesize')),
                ('field_file_type', models.CharField(db_column='_file_type', max_length=4)),
            ],
            options={
                'db_table': 'article_files',
                'managed': False,
            },
        ),
    ]
